AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  SAM template for DevSpaces Auth about compute resources

Parameters:
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String
  DomainName:
    Type: String
  UserPool:
    Type: String
  UserPoolArn:
    Type: String
  CorsOrigin:
    Type: String
  DevSpacesCLIClient:
    Type: String
  StackName:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: v1
      Auth:
        Authorizers:
          OAuth2Authorizer:
            AuthorizationScopes:
              - "openid"
              - "profile"
              - "email"
            JwtConfiguration:
              Audience:
                - !Ref DevSpacesCLIClient
              Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
            IdentitySource: "$request.querystring.token"
        DefaultAuthorizer: OAuth2Authorizer
      CorsConfiguration:
        AllowHeaders: 
          - Authorization
        AllowMethods: 
          - GET
          - OPTIONS
        AllowOrigins:
          - !Sub "${CorsOrigin}"

  DNSApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArn
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  HttpApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties: 
      ApiId: !Ref ApiGateway
      DomainName: !Ref DNSApiDomainName
      Stage: !Ref ApiGateway.Stage


  #
  # Functions
  #

  UpdateDNSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../functions/update
      Handler: main.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          HOSTED_ZONE_ID: !Ref HostedZoneId
      Policies:
        - Statement:
            - Effect: Allow
              Action: route53:ListHostedZonesByName
              Resource: "*"
            - Effect: Allow
              Action: route53:ChangeResourceRecordSets
              Resource: "*"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /update
            Method: GET
            ApiId: !Ref ApiGateway
            Auth:
              Authorizer: OAuth2Authorizer
            RouteSettings:
              ThrottlingRateLimit: 10

Outputs:
  DNSApiRegionalDomainName:
    Value: !GetAtt DNSApiDomainName.RegionalDomainName

  DNSApiRegionalHostedZoneId:
    Value: !GetAtt DNSApiDomainName.RegionalHostedZoneId

  ApiGateway:
    Value: !Ref ApiGateway
